### ISSUE TITLE
not reading *_config.json files

### ISSUE THREAD

**Issue by genderup** [kjk/fofou#3]
Running it on my local machine, using the sumatrapdf_config.json file, as well as a config I created based on that, I get the following error. 

2014/07/25 07:21:48 Failed to read forum configs, err: No forums configured!

{
    "Title":"Funny Forums",
    "ForumUrl":"funny",
    "WebsiteUrl":"http://localhost:5010",
    "Tagline":"so funny",
    "DataDir":"Funny",
    "AdminTwitterUser":"bblah blah",
    "Disabled":false,
    "BannedIps": ["^118\.248\..*"],
    "BannedWords": ["not funny", "stupid"]
}

**Comment by kjk** [comment]
The software is no longer maintained.
