### ISSUE TITLE
Option to report spam required

### ISSUE THREAD

**Issue by SumatraPeter** [kjk/fofou#5]
Wanted to report [this post](http://forums.fofou.org/sumatrapdf/topic?id=3185416) but fofou seems to lack the basic option to report spam which every forum software needs.

**Comment by kjk** [comment]
Yeah, it became a problem recently but fofou, the software, is pretty much done.

I monitor all posts via rss feed and delete spam pretty quickly.

Ultimately I should switch sumatra forums to discourse.org or some other hosted software that requires login to post but it's work to setup and migrate posts.

At the time I wrote fofou there weren't good options for simple forum software, today things are different.
