### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by moisespsena** [kjk/fofou#6]
Hello!
My system is Debian 8.6 amd64.

```bash
go version
go version go1.8.3 linux/amd64
```

I tried to run but it made a mistake. Look.

```bash
go get github.com/kjk/fofou
cd go-work/src/github.com/kjk/fofou
scripts/run.sh

0 topics, 0 posts in forum "sumatrapdf"
added forum sumatrapdf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7b3bb0]

goroutine 1 [running]:
main.main()
        /home/moi/go-work/src/github.com/kjk/fofou/main.go:415 +0x580
```

**Comment by kjk** [comment]
This is the line: https://github.com/kjk/fofou/blob/master/main.go#L415

You didn't provide AWS credentials in config.json.

Also, as mentioned in [readme.md](https://github.com/kjk/fofou/blob/master/readme.md), I no longer work on fofou.

You're free to use the code but you're on your own if there are problems.

**Comment by moisespsena** [comment]
Ok. Thanks!

I was interested in the project, I want to modify it to a private forum, something like for intranet discussions. From your point of view your project can be a good starting point for this?

**Comment by kjk** [comment]
If all you need is a simple forum this is a good start. The code is really small so easy to extend. I've been running it for years on http://forums.fofou.org/sumatrapdf on $5/month Digital Ocean server.
